name: CI-Autbuild

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@master
      
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: MSBuild
      working-directory: /
      run:  msbuild ./UltimateStreamManager.sln -property:Configuration=Debug -t:restore

