name: CI-AutoBuild

on: 
    push:
        branches:
        - master
        tags-ignore:
        - '*'

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v1.2.0
      
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[16.4,16.5)'

    - name: Restore NuGet packages
      run:  msbuild ./UltimateStreamManager.sln -t:restore
      
    - name: Build in Release
      run: msbuild ./UltimateStreamManager.sln -t:build -property:Configuration=Release -p:Platform=x86 -p:AllowedReferenceRelatedFileExtensions=none
    
    - name: Publish artifacts
      uses: actions/upload-artifact@v1
      with:
        name: binaries
        path: UltimateStreamMgr/bin/x86/Release

    - name: Install NuGet client
      uses: nuget/setup-nuget@v1
    
    - name: Generate NuGet package
      working-directory:  ./UltimateStreamMgr
      run: |
        $version = (git describe --tags)
        nuget pack UltimateStreamMgr-Beta.nuspec -Version $version

    - name: Add private GitHub registry to NuGet
      run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/Tibec/index.json -Username Tibec -Password ${{ secrets.GITHUB_TOKEN }}

    - name: Push generated package to GitHub registry
      working-directory:  ./UltimateStreamMgr
      run: nuget push *.nupkg -Source "GPR" -SkipDuplicate
