name: CI-AutoBuild

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@master
      
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Restore NuGet packages
      run:  msbuild ./UltimateStreamManager.sln -t:restore
      
    - name: Build in Release
      run: msbuild ./UltimateStreamManager.sln -t:build -property:Configuration=Release  

